name: flutter_handle_file
description: Flutter plugin project to help with associating files with your app and handling the opening of such files.
version: 0.3.0
homepage: https://github.com/nbonamy/flutter_handle_file

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: fr.bonamy.handlefile
        pluginClass: HandleFilePlugin
      ios:
        pluginClass: HandleFilePlugin
